services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  fronted:
    build: ./fronted
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
